### ISSUE TITLE
Question: What licensing is this project?

### ISSUE THREAD

**Issue by jrmiller82** [justinian/dice#4]
MIT? BSD? All rights reseved? Etc...

**Comment by justinian** [comment]
MIT. I'll add a license file to make that explicit.

**Comment by jrmiller82** [comment]
Thanks!

**Comment by justinian** [comment]
No problem! Hope you find it useful.

**Comment by jrmiller82** [comment]
I need to look at it closer. I'm writing a game master utility in go and your library might be useful. Thanks for keeping it actually free by using the MIT license.
